AllCops:
  RunRailsCops: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'tmp/*'
   - 'node_modules/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
